version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/sms
      SPRING_DATASOURCE_USERNAME: sms_user
      SPRING_DATASOURCE_PASSWORD: 12345
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: sms_user
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: sms
    ports:
      - "5432:5432"